version: '3.7'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - packages
    environment:
      - DATABASE_URL="postgresql://neondb_owner:Ox6gIQX7EerK@ep-silent-band-a12n2ixy.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
      - SECRET_KEY="TESTIMONIALS_SECRET_KEY"

  packages:
    build:
      context: ./packages
      dockerfile: Dockerfile
      target: build
    volumes:
      - ./packages:/packages
    command: ["tsc", "-b"]